---
title: "STAA 551 Assignment 3, Fall 2019"
output: pdf_document
---

```{r setup, include=FALSE, echo=TRUE}
```


#### Name: 
####

1.  A study was conducted involving 97 men with prostate cancer who were due to receive a radical prostatectomy.  The purpose of this study was to predict the logarithm of the prostate specific antigen (`lpsa`).  Eight predictor variables were considered for the study, but for this problem, we will only use `lcavol`,`lweight`, `age`, `lbph`, and `lcp`.  This data set (`prostate`) is contained in the `faraway` package, where descriptions of these variables are given.      


    (a)  Obtain a matrix of scatter plots for all of the variables mentioned above.  Based on this graph, which predictors would you expect to be helpful in explaining the variability in the response (`lpsa`)?  Justify your answer. 


    (b)  Use R to fit a linear model for `lpsa`, using all five of the predictor variables.  State the model for this regression and the fitted regression equation.


    (c)  Compute the hat matrix for the model in (b) using R.  Print the first 5 rows and 5 columns of the hat matrix.  Confirm that the hat matrix is of the correct dimensions. 


    (d)  Use R to confirm the properties of the hat matrix (symmetric, idempotent, rows sum to $1$, diagonal elements sum to $p$) for this study. You only need to print out 5 rows and 10-15 columns of appropriate calculations for this.


    (e)  Use the hat matrix found in (c) to compute the fitted Y-values.  Compute the correlation between the Y-values and the fitted Y-values, and confirm that the square of the correlation coefficient is the same as the Multiple R-squared on the summary. 

    (f)   Use the hat matrix again to compute the sample residuals, then compute the residual standard error from those sample residuals.  Check to see that it matches the residual standard error on the summary.  Note, there may be a small amount of rounding error, which we will address later.
    

2.  Use the fitted model from Problem 1 to complete the following:  


    (a)  Complete the general test for the whole model (all predictors).  Give each of the following: (1) both hypotheses, (2) the ANOVA table, converted to the simplest version for conducting this test (i.e. containing only rows for sources of variation: regression, residual and total corrected), (3) the value of the test statistic, (4) the p-value, (5) conclusions based on the p-value.


    (b)  Consider simplifying this model by eliminating `age` as a predictor.  Call this model 2b.  We wish to compare model 2b to the model in (a).  That is, we wish to test whether removing the predictor `age` from the full model significantly reduces the explained variation.  You can do this based on the summary of the `lm` object from part (a).  Give each of the following: (1) the full and reduced models, (2) both hypotheses, (3) the value of the test statistic, (4) the p-value, (5) conclusions based on the p-value.
    
    (c)  Now consider greatly simplifying the model by eliminating `age`, `lbph`, and `lcp` as predictors.  Call this model 2c.  We wish to compare model 2c to the model in (a).  You can do this based on the ANOVA table for the model in (a), provided the predictors were entered in an appropriate order.  Give each of the following: (1) the full and reduced models, (2) both hypotheses, (3) the appropriate sums of squares and degrees of freedom, (4) the value of the F statistic, (5) the p-value, (6) conclusions based on the p-value. 


3.  Consider the smallest model from Problem 2 (the model containing only `lcavol` and `lweight`).


    (a) Using the `hatvalues` function on the `lm` object, compute the leverage values and store them in a vector.  Then compute the mean of the leverage values and show that it is equal to $\frac{p}{n}$.  


    (b) Determine the observation numbers for which leverage is greater than $\frac{2p}{n}$. These are leverage points.  What does a large leverage point indicate about an observation? 


    (c)  Examine the externally studentized residuals to see if any large residuals correspond to leverage points.  Based on this, are any of the points in (b) bad leverage points?  


    (d)  Compute and graph the Cook’s distances for this model, as we did in class.  Do any of the leverage points also have large Cook’s distances?  (Use your best judgement for a cutoff value!).


    (e)  Compute the DFBETAS and use those to identify influential observations. Consider this a "large" data set for this purpose. 


    (f)  Based on your answers to (a)-(e), are there any observations that you think warrant additional consideration?  Justify your answer.  

